#!/usr/bin/env bash
# displays the content of the file /etc/passwd, filters username, user id and home directory path for the user.

while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
