#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
while [ $i -le 12 ]
do
	echo "Hour: $i"

	j=1
	while [ $j -lt 60 ]
	do
		echo "$j"
		((j++))
	done
	((i++))
done
